name: Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ./src
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../github/requirements.txt

    - name: Build
      run: pyinstaller --noconfirm --onefile --noconsole --name "Discord Music Status" --icon="icon.ico" --version-file="../github/ver.txt" --add-data "icon.ico;." main.py

    - name: Upload
      uses: svenstaro/upload-release-action@2.11.2
      with:
        file: "./src/dist/Discord Music Status.exe"
        asset_name: "Discord Music Status (Windows Media)"
        overwrite: true
        update_latest_release: true

  build-v2:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ./src
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../github/requirements.txt

    - name: Build
      run: pyinstaller --noconfirm --onefile --noconsole --name "Discord Music Status v2" --icon="icon.ico" --version-file="../github/ver.txt" --add-data "icon.ico;." "v2/main.py"

    - name: Upload
      uses: svenstaro/upload-release-action@2.11.2
      with:
        file: "./src/dist/Discord Music Status v2.exe"
        asset_name: "Discord Music Status (Browser Media)"
        overwrite: true
        update_latest_release: true

  build-v2-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create archive
        run: |
          mkdir chrome_build
          cp -r src/v2/chrome/* chrome_build/
          cd chrome_build
          zip -r ../chrome.zip .

      - name: Upload to Release
        uses: xresloader/upload-to-github-release@v1
        with:
          file: chrome.zip
          overwrite: true
          update_latest_release: true
